### PR TITLE
Peterbell

### PR DESCRIPTION
**Pull request by PeterBell**

### CODE REVIEW

**Comment by pfarrell** [comment]
Where are the unit tests?!!?

**Comment by PeterBell** [comment]
Looks good enough to me - shall we :ship: it?

**Comment by PeterBell** [comment]
Good point @pfarrell - let me add them

**Comment by EricHype** [comment]
@pfarrell : Corporate wants this out yesterday, no time!

**Comment by pfarrell** [comment]
Nice.  thanks @PeterBell.  :shipit:

**Comment by PeterBell** [comment]
Always got time for tests @pfarrell - please review and give me a :+1:

**Comment by pfarrell** [comment]
:+1:

**Pull request merged**
